/**
 * Excel file parser for NZCB Commitment Reporting forms.
 *
 * Supports two formats:
 *   Format A - Original 12-tab form (WorldGBC NZCB Cmt 2024 Reporting Form)
 *   Format B - Simplified templates (generated by generate_simplified_template.py)
 *
 * Auto-detects format based on sheet names.
 */

import * as XLSX from "xlsx";
import { FormData, defaultFormValues } from "@/lib/schema";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

type Sheet = XLSX.WorkSheet;

/** Read cell value by address string (e.g. "B3"). Returns undefined if empty. */
function cellVal(ws: Sheet, addr: string): unknown {
  const cell = ws[addr];
  if (!cell) return undefined;
  return cell.v;
}

/** Read cell value by row/col (1-indexed). */
function cellRC(ws: Sheet, row: number, col: number): unknown {
  const addr = XLSX.utils.encode_cell({ r: row - 1, c: col - 1 });
  const cell = ws[addr];
  if (!cell) return undefined;
  return cell.v;
}

/** Convert a value to number, returning fallback if not parseable. */
function toNum(v: unknown, fallback = 0): number {
  if (v === undefined || v === null || v === "") return fallback;
  const n = Number(v);
  return isNaN(n) ? fallback : n;
}

/** Convert a value to string, returning fallback if empty. */
function toStr(v: unknown, fallback = ""): string {
  if (v === undefined || v === null) return fallback;
  return String(v).trim();
}

/** Convert a Yes/No string to boolean. */
function toBool(v: unknown): boolean {
  const s = toStr(v).toLowerCase();
  return s === "yes" || s === "true" || s === "1";
}

/**
 * Search column A (or a specified column) for a row containing the given label.
 * Returns the 1-indexed row number or -1 if not found.
 */
function findRowByLabel(
  ws: Sheet,
  label: string,
  searchCol = 1,
  startRow = 1,
  endRow = 200
): number {
  const lowerLabel = label.toLowerCase();
  for (let r = startRow; r <= endRow; r++) {
    const val = toStr(cellRC(ws, r, searchCol)).toLowerCase();
    if (val.includes(lowerLabel)) return r;
  }
  return -1;
}

/**
 * Convert an Excel date serial number or string to a date string (YYYY-MM-DD).
 */
function toDateStr(v: unknown): string {
  if (v === undefined || v === null || v === "") return "";
  if (typeof v === "number") {
    // Excel serial date
    const date = XLSX.SSF.parse_date_code(v);
    if (date) {
      const y = date.y;
      const m = String(date.m).padStart(2, "0");
      const d = String(date.d).padStart(2, "0");
      return `${y}-${m}-${d}`;
    }
  }
  // Try to parse as string date
  const s = String(v).trim();
  // If already in YYYY-MM-DD format, return as-is
  if (/^\d{4}-\d{2}-\d{2}$/.test(s)) return s;
  // Try DD/MM/YYYY
  const dmy = s.match(/^(\d{1,2})[/\-.](\d{1,2})[/\-.](\d{4})$/);
  if (dmy) {
    return `${dmy[3]}-${dmy[2].padStart(2, "0")}-${dmy[1].padStart(2, "0")}`;
  }
  return s;
}

// ---------------------------------------------------------------------------
// Format detection
// ---------------------------------------------------------------------------

type ExcelFormat = "A" | "B" | "unknown";

function detectFormat(sheetNames: string[]): ExcelFormat {
  const names = sheetNames.map((n) => n.toLowerCase().trim());

  // Format B: simplified templates
  if (
    names.some((n) => n.includes("1. details")) &&
    names.some((n) => n.includes("2. portfolio"))
  ) {
    return "B";
  }

  // Format A: original 12-tab form
  if (
    names.some((n) => n.includes("1. entity details") || n.includes("entity details")) &&
    names.some((n) => n.includes("2. commit") || n.includes("commit"))
  ) {
    return "A";
  }

  return "unknown";
}

function findSheet(wb: XLSX.WorkBook, partialName: string): Sheet | null {
  const lower = partialName.toLowerCase();
  const name = wb.SheetNames.find((n) => n.toLowerCase().includes(lower));
  return name ? wb.Sheets[name] : null;
}

// ---------------------------------------------------------------------------
// Format B parser (simplified templates)
// ---------------------------------------------------------------------------

function parseFormatB(wb: XLSX.WorkBook): Partial<FormData> {
  const data: Partial<FormData> = {};

  // -- Tab 1: Details --
  const ws1 = findSheet(wb, "1. details");
  if (ws1) {
    // Fixed positions from generate_simplified_template.py:
    // Row 3: Entity name, Row 4: Signatory ID, Row 5: Year joined,
    // Row 6: Commitment version, Row 7: Submitter name, Row 8: Submitter email
    // But we also search by label for resilience

    const entityRow = findRowByLabel(ws1, "entity name");
    if (entityRow > 0) {
      const val = toStr(cellRC(ws1, entityRow, 2));
      if (val && !val.includes("[Pre-fill")) data.entityName = val;
    }

    const sigRow = findRowByLabel(ws1, "signatory id");
    if (sigRow > 0) data.signatoryId = toStr(cellRC(ws1, sigRow, 2));

    const yearRow = findRowByLabel(ws1, "year joined");
    if (yearRow > 0) {
      const v = toNum(cellRC(ws1, yearRow, 2), 0);
      if (v >= 2018 && v <= 2030) data.yearJoined = v;
    }

    const versionRow = findRowByLabel(ws1, "commitment version");
    if (versionRow > 0) {
      const v = toStr(cellRC(ws1, versionRow, 2));
      if (v === "2019" || v === "2021") data.commitmentVersion = v;
    }

    const submNameRow = findRowByLabel(ws1, "submitter name");
    if (submNameRow > 0) data.submitterName = toStr(cellRC(ws1, submNameRow, 2));

    const submEmailRow = findRowByLabel(ws1, "submitter email");
    if (submEmailRow > 0) data.submitterEmail = toStr(cellRC(ws1, submEmailRow, 2));

    // Climate initiatives
    const initiatives: string[] = [];
    const ep100Row = findRowByLabel(ws1, "ep100");
    if (ep100Row > 0 && toBool(cellRC(ws1, ep100Row, 2))) initiatives.push("EP100");

    const sbtiRow = findRowByLabel(ws1, "sbti");
    if (sbtiRow > 0 && toBool(cellRC(ws1, sbtiRow, 2))) initiatives.push("SBTi");

    const rtzRow = findRowByLabel(ws1, "race to zero");
    if (rtzRow > 0 && toBool(cellRC(ws1, rtzRow, 2))) initiatives.push("Race to Zero");

    const cpRow = findRowByLabel(ws1, "the climate pledge");
    if (cpRow > 0 && toBool(cellRC(ws1, cpRow, 2)))
      initiatives.push("The Climate Pledge");

    if (initiatives.length > 0) data.climateInitiatives = initiatives;

    // Consent
    const consentRow = findRowByLabel(ws1, "i consent");
    if (consentRow > 0) data.consent = toBool(cellRC(ws1, consentRow, 2));

    // Marketing opt-in
    const marketingRow = findRowByLabel(ws1, "marketing opt-in");
    if (marketingRow > 0)
      data.marketingOptIn = toBool(cellRC(ws1, marketingRow, 2));

    // Signature
    const sigSignRow = findRowByLabel(ws1, "digital signature");
    if (sigSignRow > 0) data.signature = toStr(cellRC(ws1, sigSignRow, 2));
  }

  // -- Tab 2: Portfolio --
  const ws2 = findSheet(wb, "2. portfolio");
  if (ws2) {
    const targetRow = findRowByLabel(ws2, "target year");
    if (targetRow > 0) {
      const v = toNum(cellRC(ws2, targetRow, 2), 0);
      if (v >= 2025 && v <= 2050) data.targetYear = v;
    }

    const areaRow = findRowByLabel(ws2, "area measurement");
    if (areaRow > 0) data.areaMeasurement = toStr(cellRC(ws2, areaRow, 2));

    const covRow = findRowByLabel(ws2, "coverage");
    if (covRow > 0) {
      const v = toStr(cellRC(ws2, covRow, 2));
      if (v === "Common areas only" || v === "Whole building") {
        data.coverageType = v as "All assets" | "Selected assets";
      }
    }

    // Asset table: find the header row "Asset Type"
    const assetHeaderRow = findRowByLabel(ws2, "asset type");
    if (assetHeaderRow > 0) {
      const assets: Array<{
        type: string;
        count: number;
        area: number;
        change: number;
        reason: string;
      }> = [];
      // The template has 5 asset types after the header
      for (let r = assetHeaderRow + 1; r <= assetHeaderRow + 10; r++) {
        const type = toStr(cellRC(ws2, r, 1));
        if (!type) break;
        assets.push({
          type,
          count: toNum(cellRC(ws2, r, 2)),
          area: toNum(cellRC(ws2, r, 3)),
          change: toNum(cellRC(ws2, r, 4)),
          reason: toStr(cellRC(ws2, r, 5)),
        });
      }
      if (assets.length > 0) data.assets = assets;
    }

    // Portfolio changes
    const addedRow = findRowByLabel(ws2, "assets added");
    if (addedRow > 0) data.assetsAdded = toNum(cellRC(ws2, addedRow, 2));

    const removedRow = findRowByLabel(ws2, "assets removed");
    if (removedRow > 0) data.assetsRemoved = toNum(cellRC(ws2, removedRow, 2));

    const reasonRow = findRowByLabel(ws2, "reason for change");
    if (reasonRow > 0) data.changeReason = toStr(cellRC(ws2, reasonRow, 2));
  }

  // -- Tab 3: Performance --
  const ws3 = findSheet(wb, "3. performance");
  if (ws3) {
    const fromRow = findRowByLabel(ws3, "reporting period");
    if (fromRow > 0) {
      // "Reporting period - From" at fromRow, "Reporting period - To" at fromRow+1
      data.reportingPeriodFrom = toDateStr(cellRC(ws3, fromRow, 2));
      const toRow = findRowByLabel(ws3, "reporting period", 1, fromRow + 1);
      if (toRow > 0) data.reportingPeriodTo = toDateStr(cellRC(ws3, toRow, 2));
    }

    const ghgRow = findRowByLabel(ws3, "ghg accounting");
    if (ghgRow > 0) data.ghgStandard = toStr(cellRC(ws3, ghgRow, 2));

    // Operational carbon data table
    const opData = { ...defaultFormValues.operationalData };

    // Find metric rows by label in column A
    const elecRow = findRowByLabel(ws3, "electricity");
    if (elecRow > 0) {
      opData.totalElectricity = toNum(cellRC(ws3, elecRow, 3));
      opData.renewableOnSite = toNum(cellRC(ws3, elecRow, 4));
      opData.renewableOffSite = toNum(cellRC(ws3, elecRow, 5));
    }

    const fuelsRow = findRowByLabel(ws3, "fuels");
    if (fuelsRow > 0) {
      // Map "Fuels" total to natural gas as a reasonable default
      // (the simplified template combines all fuels into one row)
      opData.totalNaturalGas = toNum(cellRC(ws3, fuelsRow, 3));
    }

    const distRow = findRowByLabel(ws3, "district heating");
    if (distRow > 0) {
      opData.totalDistrictHeatingCooling = toNum(cellRC(ws3, distRow, 3));
    }

    const s1Row = findRowByLabel(ws3, "scope 1");
    if (s1Row > 0) {
      opData.scope1Emissions = toNum(cellRC(ws3, s1Row, 3));
      opData.carbonOffsets = toNum(cellRC(ws3, s1Row, 6));
    }

    const s2Row = findRowByLabel(ws3, "scope 2");
    if (s2Row > 0) {
      opData.scope2Emissions = toNum(cellRC(ws3, s2Row, 3));
    }

    data.operationalData = opData;

    // Refrigerant
    const refRow = findRowByLabel(ws3, "refrigerant emissions included");
    if (refRow > 0) {
      data.refrigerantEmissions = toBool(cellRC(ws3, refRow, 2)) ? 1 : 0;
    }
    const refQtyRow = findRowByLabel(ws3, "refrigerant emissions quantity");
    if (refQtyRow > 0) {
      data.refrigerantQuantity = toNum(cellRC(ws3, refQtyRow, 2));
    }

    // Metered data
    const meteredRow = findRowByLabel(ws3, "% of data from metered");
    if (meteredRow > 0) {
      data.meteredDataPercent = toNum(cellRC(ws3, meteredRow, 2));
    }

    const nonMetRow = findRowByLabel(ws3, "non-metered data source");
    if (nonMetRow > 0) {
      data.nonMeteredSource = toStr(cellRC(ws3, nonMetRow, 2));
    }

    // Verification
    const vmRow = findRowByLabel(ws3, "verification method");
    if (vmRow > 0) data.verificationMethod = toStr(cellRC(ws3, vmRow, 2));

    const vnRow = findRowByLabel(ws3, "verifier name");
    if (vnRow > 0) data.verifierName = toStr(cellRC(ws3, vnRow, 2));

    const vdRow = findRowByLabel(ws3, "verification date");
    if (vdRow > 0) data.verifierDate = toDateStr(cellRC(ws3, vdRow, 2));

    const vlRow = findRowByLabel(ws3, "link to verification");
    if (vlRow > 0) data.verifierLink = toStr(cellRC(ws3, vlRow, 2));

    const pdRow = findRowByLabel(ws3, "public disclosure");
    if (pdRow > 0) data.publicDisclosureLink = toStr(cellRC(ws3, pdRow, 2));

    // Section 3B: Embodied carbon assets
    const ecHeaderRow = findRowByLabel(ws3, "asset name");
    if (ecHeaderRow > 0) {
      const ecAssets: Array<{
        name: string;
        completionYear: number;
        buildingType: string;
        area: number;
        upfrontCarbon: number;
        calculationTool: string;
        database: string;
        lcaConducted: boolean;
      }> = [];
      for (let r = ecHeaderRow + 1; r <= ecHeaderRow + 10; r++) {
        const name = toStr(cellRC(ws3, r, 1));
        if (!name) break;
        ecAssets.push({
          name,
          completionYear: toNum(cellRC(ws3, r, 2)),
          buildingType: toStr(cellRC(ws3, r, 3)),
          area: toNum(cellRC(ws3, r, 4)),
          upfrontCarbon: toNum(cellRC(ws3, r, 5)),
          calculationTool: toStr(cellRC(ws3, r, 6)),
          database: toStr(cellRC(ws3, r, 7)),
          lcaConducted: toBool(cellRC(ws3, r, 8)),
        });
      }
      if (ecAssets.length > 0) data.embodiedCarbonAssets = ecAssets;
    }
  }

  // -- Tab 4: Actions --
  const ws4 = findSheet(wb, "4. actions");
  if (ws4) {
    // Action table header at row 3: "Action category", ...
    const headerRow = findRowByLabel(ws4, "action category");
    if (headerRow > 0) {
      const actions: Array<{
        category: string;
        target: string;
        milestones: string;
        progress: string;
        status: string;
        scope: string;
        expectedCompletion: string;
        energySaving: number;
        carbonReduction: number;
      }> = [];
      for (let r = headerRow + 1; r <= headerRow + 20; r++) {
        const cat = toStr(cellRC(ws4, r, 1));
        if (!cat) break;
        actions.push({
          category: cat,
          target: toStr(cellRC(ws4, r, 2)),
          milestones: toStr(cellRC(ws4, r, 3)),
          progress: toStr(cellRC(ws4, r, 4)),
          status: toStr(cellRC(ws4, r, 5)) || "Not started",
          scope: toStr(cellRC(ws4, r, 6)) || "Asset level",
          expectedCompletion: toStr(cellRC(ws4, r, 7)),
          energySaving: toNum(cellRC(ws4, r, 8)),
          carbonReduction: toNum(cellRC(ws4, r, 9)),
        });
      }
      if (actions.length > 0) data.actions = actions;
    }

    // Additional questions
    const qaRow = findRowByLabel(ws4, "qa undertaken");
    if (qaRow > 0) data.qaUndertaken = toBool(cellRC(ws4, qaRow, 2));

    const qaDetRow = findRowByLabel(ws4, "qa details");
    if (qaDetRow > 0) data.qaDetails = toStr(cellRC(ws4, qaDetRow, 2));

    const elecRow = findRowByLabel(ws4, "electrification plans");
    if (elecRow > 0) data.electrificationPlans = toBool(cellRC(ws4, elecRow, 2));

    const elecDetRow = findRowByLabel(ws4, "electrification details");
    if (elecDetRow > 0)
      data.electrificationDetails = toStr(cellRC(ws4, elecDetRow, 2));

    const offsetRow = findRowByLabel(ws4, "carbon offset type");
    if (offsetRow > 0) data.offsetType = toStr(cellRC(ws4, offsetRow, 2));
  }

  // -- Tab 5: Advocacy --
  const ws5 = findSheet(wb, "5. advocacy");
  if (ws5) {
    const progRow = findRowByLabel(ws5, "advocacy programme");
    if (progRow > 0) {
      const v = toStr(cellRC(ws5, progRow, 2)).toLowerCase();
      data.advocacyProgramme = v === "yes";
    }

    // Advocacy actions table: header row has "Stakeholder type"
    const headerRow = findRowByLabel(ws5, "stakeholder type");
    if (headerRow > 0) {
      const advocacyActions: Array<{
        stakeholderType: string;
        actionType: string;
        description: string;
        link: string;
      }> = [];
      for (let r = headerRow + 1; r <= headerRow + 10; r++) {
        const st = toStr(cellRC(ws5, r, 1));
        if (!st) break;
        advocacyActions.push({
          stakeholderType: st,
          actionType: toStr(cellRC(ws5, r, 2)),
          description: toStr(cellRC(ws5, r, 3)),
          link: toStr(cellRC(ws5, r, 4)),
        });
      }
      if (advocacyActions.length > 0) data.advocacyActions = advocacyActions;
    }

    // Additional info - find the merged text area after "Any additional information"
    const addInfoRow = findRowByLabel(ws5, "additional information");
    if (addInfoRow > 0) {
      // The text area is typically 2 rows below the label
      const infoVal = toStr(cellRC(ws5, addInfoRow + 2, 1));
      if (infoVal) data.additionalInfo = infoVal;
    }
  }

  // -- Tab 6: EP100 (optional) --
  const ws6 = findSheet(wb, "6. ep100");
  if (ws6) {
    const tyRow = findRowByLabel(ws6, "ep100 target year");
    if (tyRow > 0) {
      const v = toNum(cellRC(ws6, tyRow, 2), 0);
      if (v > 0) data.ep100TargetYear = v;
    }

    const byRow = findRowByLabel(ws6, "ep100 baseline year");
    if (byRow < 0) {
      // Try alternate label
      const altRow = findRowByLabel(ws6, "baseline year");
      if (altRow > 0) data.ep100BaselineYear = toNum(cellRC(ws6, altRow, 2), 0);
    } else {
      data.ep100BaselineYear = toNum(cellRC(ws6, byRow, 2), 0);
    }

    const notesRow = findRowByLabel(ws6, "additional notes");
    if (notesRow > 0) data.ep100Actions = toStr(cellRC(ws6, notesRow, 2));
  }

  return data;
}

// ---------------------------------------------------------------------------
// Format A parser (original 12-tab form) - best-effort
// ---------------------------------------------------------------------------

function parseFormatA(wb: XLSX.WorkBook): Partial<FormData> {
  const data: Partial<FormData> = {};

  // Tab "1. Entity Details" - entity name typically at D6
  const ws1 =
    findSheet(wb, "1. entity details") || findSheet(wb, "entity details");
  if (ws1) {
    // Try known positions first, then search by label
    const d6 = toStr(cellVal(ws1, "D6"));
    if (d6) {
      data.entityName = d6;
    } else {
      const entRow = findRowByLabel(ws1, "entity name");
      if (entRow > 0) {
        // Try columns B, C, D for the value
        data.entityName =
          toStr(cellRC(ws1, entRow, 4)) ||
          toStr(cellRC(ws1, entRow, 3)) ||
          toStr(cellRC(ws1, entRow, 2));
      }
    }

    // Try to find signatory ID
    const sigRow = findRowByLabel(ws1, "signatory");
    if (sigRow > 0) {
      data.signatoryId =
        toStr(cellRC(ws1, sigRow, 4)) ||
        toStr(cellRC(ws1, sigRow, 3)) ||
        toStr(cellRC(ws1, sigRow, 2));
    }

    // Submitter info
    const subRow = findRowByLabel(ws1, "contact");
    if (subRow > 0) {
      data.submitterName =
        toStr(cellRC(ws1, subRow, 4)) ||
        toStr(cellRC(ws1, subRow, 3)) ||
        toStr(cellRC(ws1, subRow, 2));
    }
    const emailRow = findRowByLabel(ws1, "email");
    if (emailRow > 0) {
      data.submitterEmail =
        toStr(cellRC(ws1, emailRow, 4)) ||
        toStr(cellRC(ws1, emailRow, 3)) ||
        toStr(cellRC(ws1, emailRow, 2));
    }
  }

  // Tab "2. Commit" - try to get target year
  const ws2 = findSheet(wb, "2. commit") || findSheet(wb, "commit");
  if (ws2) {
    const tyRow = findRowByLabel(ws2, "target year");
    if (tyRow > 0) {
      for (let c = 2; c <= 6; c++) {
        const v = toNum(cellRC(ws2, tyRow, c), 0);
        if (v >= 2025 && v <= 2050) {
          data.targetYear = v;
          break;
        }
      }
    }
  }

  // Tab "3. Disclose" - operational carbon
  const ws3 = findSheet(wb, "3. disclose") || findSheet(wb, "disclose");
  if (ws3) {
    const opData = { ...defaultFormValues.operationalData };

    const elecRow = findRowByLabel(ws3, "electricity");
    if (elecRow > 0) {
      // Scan columns for a numeric value
      for (let c = 2; c <= 8; c++) {
        const v = toNum(cellRC(ws3, elecRow, c), 0);
        if (v > 0) {
          opData.totalElectricity = v;
          break;
        }
      }
    }

    const gasRow = findRowByLabel(ws3, "natural gas");
    if (gasRow > 0) {
      for (let c = 2; c <= 8; c++) {
        const v = toNum(cellRC(ws3, gasRow, c), 0);
        if (v > 0) {
          opData.totalNaturalGas = v;
          break;
        }
      }
    }

    const s1Row = findRowByLabel(ws3, "scope 1");
    if (s1Row > 0) {
      for (let c = 2; c <= 8; c++) {
        const v = toNum(cellRC(ws3, s1Row, c), 0);
        if (v > 0) {
          opData.scope1Emissions = v;
          break;
        }
      }
    }

    const s2Row = findRowByLabel(ws3, "scope 2");
    if (s2Row > 0) {
      for (let c = 2; c <= 8; c++) {
        const v = toNum(cellRC(ws3, s2Row, c), 0);
        if (v > 0) {
          opData.scope2Emissions = v;
          break;
        }
      }
    }

    data.operationalData = opData;
  }

  // Tab "6. Advocate" - advocacy data
  const ws6 = findSheet(wb, "6. advocate") || findSheet(wb, "advocate");
  if (ws6) {
    // Try to detect if advocacy programme is in place
    const progRow = findRowByLabel(ws6, "advocacy");
    if (progRow > 0) {
      data.advocacyProgramme = true;
    }
  }

  return data;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface ParseResult {
  format: "A" | "B" | "unknown";
  data: Partial<FormData>;
  fieldsPopulated: number;
  warnings: string[];
}

export async function parseExcelFile(file: File): Promise<ParseResult> {
  const buffer = await file.arrayBuffer();
  const wb = XLSX.read(buffer, { type: "array" });

  const format = detectFormat(wb.SheetNames);
  const warnings: string[] = [];

  if (format === "unknown") {
    warnings.push(
      "Could not detect a known Excel format. The file may not be a valid NZCB reporting form."
    );
    return { format: "unknown", data: {}, fieldsPopulated: 0, warnings };
  }

  let data: Partial<FormData>;
  if (format === "B") {
    data = parseFormatB(wb);
  } else {
    data = parseFormatA(wb);
    warnings.push(
      "Detected original form format (Format A). Some fields may not be fully populated. Please review and fill in any missing data."
    );
  }

  // Count populated fields
  let count = 0;
  for (const [key, value] of Object.entries(data)) {
    if (value === undefined || value === null || value === "") continue;
    if (Array.isArray(value) && value.length === 0) continue;
    if (typeof value === "object" && !Array.isArray(value)) {
      // Check nested object (e.g. operationalData)
      const hasValues = Object.values(value as Record<string, unknown>).some(
        (v) => v !== 0 && v !== "" && v !== undefined && v !== null
      );
      if (hasValues) count++;
    } else {
      count++;
    }
  }

  return { format, data, fieldsPopulated: count, warnings };
}
